# Generated by Django 2.2.14 on 2021-03-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_market'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='market',
            name='branch',
            field=models.CharField(default='Elektro', max_length=60),
        ),
    ]
