# Generated by Django 2.2.14 on 2021-03-21 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210319_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.Market'),
        ),
    ]
