# Generated by Django 2.2.14 on 2021-03-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_market_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='path',
            field=models.CharField(default='http://127.0.0.1:8000/market-product-list/', max_length=100),
        ),
    ]
