# Generated by Django 2.2.14 on 2021-03-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_item_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='path',
            field=models.CharField(default='/market-product-list/', max_length=100),
        ),
    ]
