# Generated by Django 2.2.14 on 2021-04-01 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210401_2327'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemCategory',
        ),
    ]
